// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo2VoUKKEMnrjj5xUCXjOGKQn6t0ySPGE',
    appId: '1:181665972324:web:5db7345425ff2430bedf71',
    messagingSenderId: '181665972324',
    projectId: 'sikawan-lms',
    authDomain: 'sikawan-lms.firebaseapp.com',
    storageBucket: 'sikawan-lms.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo7A1ULcOyTG89xjT0J4j43r6u8rkc-m4',
    appId: '1:181665972324:android:f91323847803ef52bedf71',
    messagingSenderId: '181665972324',
    projectId: 'sikawan-lms',
    storageBucket: 'sikawan-lms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzCEyCNYjk8Nu1b78P22NbvIrPOcSjhYc',
    appId: '1:181665972324:ios:760b8af9426e5cbcbedf71',
    messagingSenderId: '181665972324',
    projectId: 'sikawan-lms',
    storageBucket: 'sikawan-lms.firebasestorage.app',
    iosBundleId: 'com.example.sikawan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzCEyCNYjk8Nu1b78P22NbvIrPOcSjhYc',
    appId: '1:181665972324:ios:760b8af9426e5cbcbedf71',
    messagingSenderId: '181665972324',
    projectId: 'sikawan-lms',
    storageBucket: 'sikawan-lms.firebasestorage.app',
    iosBundleId: 'com.example.sikawan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo2VoUKKEMnrjj5xUCXjOGKQn6t0ySPGE',
    appId: '1:181665972324:web:280eddf6e92af207bedf71',
    messagingSenderId: '181665972324',
    projectId: 'sikawan-lms',
    authDomain: 'sikawan-lms.firebaseapp.com',
    storageBucket: 'sikawan-lms.firebasestorage.app',
  );
}
